### PR TITLE
EDMFIELD Folding

### PR DESCRIPTION
**Pull request by Warimi**
I have cleaned up the edmfield implementation and added field folding around a user defined box in the geometry.in

### CODE REVIEW

**Comment by wschreyer** [comment]
Thanks for the pull request.
You have replaced large parts of my PENeLOPE example configuration. I would suggest to move the different configurations in separate subfolders.
I'm not sure when I will find the time to do that. You are of course welcome to do it yourself.

**Comment by Warimi** [comment]
I have restored your PENeLOPE example configuration as requested, if it looks good now feel free to pull.

Thanks!

**Comment by Warimi** [comment]
I beleieve it is now fully functional as I have managed to run your PENeLOPE simulation off it locally, when ever you are comfortable merging my additions feel free.
Thanks

**Comment by wschreyer** [comment]
Merged it. Sorry about the long delay.

**Pull request merged**
