### PR TITLE
Adds additional analytical fields (mostly different B0 gradients) and now allows them to scale with time

### PR DESCRIPTION
**Pull request by dougUCN**
I saw that we now have the option to output directly to root trees and have more control over the output log fields! Really glad that's been implemented. This code has been really useful, thanks for maintaining it!

This is something I should have opened a pull request for months ago, just added some more analytical fields and now enables the scaling factor so that they're no longer forced to be static. (Back when I wasn't as familiar with this library I didn't know how to implement it)

### CODE REVIEW

**Comment by wschreyer** [comment]
Thanks, good to hear that it's useful to other people.

To make the new field classes usable you will have to include your changes to TFieldManager in the pull request. And could you add a couple of sentences in the example config explaining the new fields? People who don't want to look at the code shouldn't have to use the doxygen documentation.

I trust you have done a couple of tests to confirm the fields work as intended?

**Comment by dougUCN** [comment]
Added to TFieldManager, thanks for the reminder.

I created a config file in test/analyticalFieldTest that has a description of the fields

These fields were tested with a B Field Cut readout as well as a T2 spin decoherence time simulation (checked against other monte carlo simulations), so I have reasonable confidence that they work

**Comment by wschreyer** [comment]
Thanks, it's merged.
Looking at all those very simple fields gave me the idea of a custom field class with components defined as formulas in the config file. I'll experiment a little with that idea. If the performance is acceptable it might replace a lot of those simple field classes.

**Comment by dougUCN** [comment]
Ohhh that would be neat! I'm sure it'd be doable with that expertk parsing you have

**Pull request merged**
